import type { Database } from "bun:sqlite";

export const FOUNDATION_OPERATION_TABLES = [
  "run_execution_policies",
  "run_execution_connector_epochs",
  "work_item_mutation_guards",
  "mutation_guard_overrides",
  "authority_sessions",
  "authority_session_connector_epochs",
  "mutation_leases",
  "operation_authorizations",
  "run_lifecycle_events",
  "attempt_lifecycle_events",
  "run_checkpoints",
  "checkpoint_evidence_links",
  "checkpoint_source_revisions",
  "checkpoint_responses",
  "run_evidence",
  "run_evidence_changed_paths",
  "run_results",
  "run_result_evidence_links",
  "authority_revocations",
  "authority_termination_intents",
  "accepted_runner_events",
  "accepted_event_ack_outbox",
  "deployment_authority_state",
  "credential_wrapping_keys",
  "credential_key_rotations",
  "backup_records",
  "restore_operations",
  "backup_retention_state",
  "personal_run_presets",
  "personal_run_preset_versions",
  "personal_run_preset_gates",
  "personal_run_preset_stop_nodes",
  "project_personal_preset_defaults",
  "context_recipes",
  "context_recipe_versions",
  "context_recipe_category_limits",
  "run_configuration_snapshots",
  "context_bootstrap_envelopes",
  "context_envelope_references",
  "attempt_usage_eligibility",
  "usage_observations",
  "operational_incidents",
  "published_git_references",
  "retained_local_work_projections",
  "retained_local_work_changed_paths",
] as const;

export const FOUNDATION_OPERATION_INDEXES = [
  "one_held_mutation_guard",
  "mutation_guard_overrides_record_created",
  "active_authority_session_by_attempt",
  "authority_sessions_runner_state",
  "active_mutation_lease_by_session",
  "operation_authorizations_session_state",
  "run_checkpoints_run_created",
  "checkpoint_responses_checkpoint_created",
  "run_evidence_run_created",
  "authority_revocations_source_epoch",
  "pending_authority_termination_intents",
  "accepted_runner_events_attempt_sequence",
  "pending_accepted_event_ack_outbox",
  "active_credential_wrapping_key",
  "active_credential_key_rotations",
  "verified_backups_created",
  "active_restore_operations",
  "personal_run_presets_owner_state",
  "context_recipes_project_state",
  "usage_observations_attempt_category",
  "open_operational_incidents",
  "published_git_references_run_verified",
  "retained_local_work_runner_state",
] as const;

export const FOUNDATION_OPERATION_TRIGGERS = [
  "run_execution_policy_immutable",
  "run_execution_connector_epoch_immutable",
  "mutation_guard_identity_immutable",
  "mutation_guard_override_immutable",
  "mutation_guard_override_delete_denied",
  "authority_session_identity_immutable",
  "authority_session_connector_epoch_immutable",
  "mutation_lease_identity_immutable",
  "operation_authorization_claims_immutable",
  "run_lifecycle_event_immutable",
  "attempt_lifecycle_event_immutable",
  "run_checkpoint_immutable",
  "checkpoint_evidence_link_immutable",
  "checkpoint_source_revision_immutable",
  "checkpoint_response_immutable",
  "run_evidence_immutable",
  "run_evidence_changed_path_immutable",
  "run_result_immutable",
  "run_result_evidence_link_immutable",
  "authority_revocation_immutable",
  "authority_termination_intent_identity_immutable",
  "accepted_runner_event_immutable",
  "accepted_event_ack_identity_immutable",
  "credential_wrapping_key_material_immutable",
  "backup_manifest_immutable",
  "personal_run_preset_identity_immutable",
  "personal_run_preset_version_immutable",
  "personal_run_preset_version_delete_denied",
  "personal_run_preset_gate_immutable",
  "personal_run_preset_gate_delete_denied",
  "personal_run_preset_stop_node_immutable",
  "personal_run_preset_stop_node_delete_denied",
  "context_recipe_identity_immutable",
  "context_recipe_version_immutable",
  "context_recipe_version_delete_denied",
  "context_recipe_category_limit_immutable",
  "context_recipe_category_limit_delete_denied",
  "run_configuration_snapshot_immutable",
  "run_configuration_snapshot_delete_denied",
  "context_bootstrap_envelope_immutable",
  "context_bootstrap_envelope_delete_denied",
  "context_envelope_reference_immutable",
  "context_envelope_reference_delete_denied",
  "attempt_usage_eligibility_immutable",
  "attempt_usage_eligibility_delete_denied",
  "usage_observation_immutable",
  "usage_observation_delete_denied",
  "published_git_reference_immutable",
  "published_git_reference_delete_denied",
  "retained_local_work_identity_immutable",
  "retained_local_work_changed_path_immutable",
] as const;

const FOUNDATION_OPERATIONS_SCHEMA_SHA256 =
  "a70feb94b0c9f9be3861c586c9d23114603d4f8f6ebbed475a63715b3b076838";

const EXPECTED_COLUMNS: Readonly<
  Record<(typeof FOUNDATION_OPERATION_TABLES)[number], readonly string[]>
> = {
  run_execution_policies: [
    "run_id",
    "maximum_attempts",
    "deadline_at",
    "permit_seconds",
    "authority_session_seconds",
    "authority_renewal_seconds",
    "mutation_disconnect_grace_seconds",
    "connector_epochs_digest",
    "created_at",
  ],
  run_execution_connector_epochs: ["run_id", "connector_id", "connector_epoch"],
  work_item_mutation_guards: [
    "id",
    "coordination_record_id",
    "run_id",
    "fence",
    "state",
    "revision",
    "reserved_at",
    "released_at",
    "revoked_at",
  ],
  mutation_guard_overrides: [
    "id",
    "coordination_record_id",
    "mutation_guard_id",
    "guarded_run_id",
    "guarded_run_revision",
    "colliding_run_id",
    "colliding_run_revision",
    "guard_fence",
    "guard_revision",
    "actor_member_id",
    "reason",
    "created_at",
  ],
  authority_sessions: [
    "id",
    "attempt_id",
    "runner_id",
    "runner_epoch",
    "connection_id",
    "fence",
    "repository_mode",
    "repository_assurance",
    "connector_epochs_digest",
    "state",
    "revision",
    "issued_at",
    "expires_at",
    "renewed_at",
    "released_at",
    "revoked_at",
  ],
  authority_session_connector_epochs: ["session_id", "connector_id", "connector_epoch"],
  mutation_leases: [
    "id",
    "session_id",
    "run_id",
    "attempt_id",
    "mutation_guard_id",
    "fence",
    "state",
    "revision",
    "issued_at",
    "expires_at",
    "disconnect_grace_expires_at",
    "renewed_at",
    "released_at",
    "revoked_at",
  ],
  operation_authorizations: [
    "id",
    "session_id",
    "session_fence",
    "mutation_lease_fence",
    "operation_kind",
    "operation_digest",
    "resource_id",
    "expected_revision",
    "connector_id",
    "connector_epoch",
    "connector_scope_id",
    "connector_scope_revision",
    "connector_operation",
    "action_digest",
    "state",
    "revision",
    "issued_at",
    "expires_at",
    "consumed_at",
    "revoked_at",
  ],
  run_lifecycle_events: [
    "id",
    "run_id",
    "sequence",
    "event_kind",
    "from_state",
    "to_state",
    "reason_code",
    "actor_kind",
    "actor_id",
    "occurred_at",
  ],
  attempt_lifecycle_events: [
    "id",
    "attempt_id",
    "sequence",
    "event_kind",
    "from_state",
    "to_state",
    "reason_code",
    "exit_code",
    "signal",
    "correlation_id",
    "occurred_at",
  ],
  run_checkpoints: [
    "id",
    "run_id",
    "attempt_id",
    "reason",
    "requested_action",
    "summary",
    "runner_id",
    "worktree_identity",
    "current_commit",
    "published_remote_identity",
    "published_remote_ref",
    "published_commit",
    "published_verified_at",
    "resume_guidance",
    "created_at",
  ],
  checkpoint_evidence_links: ["checkpoint_id", "evidence_id", "ordinal"],
  checkpoint_source_revisions: ["checkpoint_id", "source_key", "source_revision"],
  checkpoint_responses: [
    "id",
    "checkpoint_id",
    "actor_kind",
    "actor_id",
    "response_kind",
    "summary",
    "created_at",
  ],
  run_evidence: [
    "id",
    "run_id",
    "attempt_id",
    "evidence_kind",
    "summary",
    "outcome",
    "repository_revision",
    "secondary_revision",
    "subject_id",
    "gate_key",
    "manifest_fingerprint",
    "remote_identity",
    "remote_ref",
    "observed_at",
    "duration_ms",
    "files_changed",
    "additions",
    "deletions",
    "dirty",
    "truncated",
    "tracked_clean",
    "untracked_clean",
    "published_commit",
    "evidence_revision",
    "evidence_digest",
    "created_at",
  ],
  run_evidence_changed_paths: ["evidence_id", "ordinal", "repository_relative_path"],
  run_results: [
    "id",
    "run_id",
    "attempt_id",
    "result_kind",
    "summary",
    "reason_code",
    "requested_action",
    "evidence_set_digest",
    "created_at",
  ],
  run_result_evidence_links: ["result_id", "evidence_id", "ordinal"],
  authority_revocations: [
    "id",
    "source_kind",
    "source_id",
    "source_epoch",
    "actor_kind",
    "actor_id",
    "disposition",
    "created_at",
  ],
  authority_termination_intents: [
    "id",
    "run_id",
    "attempt_id",
    "intent_kind",
    "reason_code",
    "semantic_digest",
    "state",
    "revision",
    "created_at",
    "dispatched_at",
    "acknowledged_at",
    "last_error_code",
  ],
  accepted_runner_events: [
    "runner_id",
    "semantic_event_id",
    "run_id",
    "attempt_id",
    "schema_version",
    "event_kind",
    "local_sequence",
    "predecessor_event_id",
    "input_hash",
    "committed_result_id",
    "disposition",
    "accepted_at",
  ],
  accepted_event_ack_outbox: [
    "id",
    "runner_id",
    "semantic_event_id",
    "result_reference",
    "semantic_digest",
    "state",
    "retry_count",
    "created_at",
    "dispatched_at",
    "acknowledged_at",
  ],
  deployment_authority_state: [
    "deployment_id",
    "singleton",
    "authority_incarnation",
    "restore_state",
    "restore_operation_id",
    "revision",
    "created_at",
    "updated_at",
  ],
  credential_wrapping_keys: [
    "id",
    "credential_class",
    "key_version",
    "wrapping_key_id",
    "algorithm",
    "nonce",
    "wrapped_key",
    "auth_tag",
    "state",
    "created_at",
    "activated_at",
    "retired_at",
  ],
  credential_key_rotations: [
    "id",
    "credential_class",
    "from_key_version",
    "to_key_version",
    "state",
    "last_credential_id",
    "processed_count",
    "revision",
    "created_at",
    "updated_at",
    "completed_at",
  ],
  backup_records: [
    "id",
    "format",
    "manifest_version",
    "deployment_fingerprint",
    "source_authority_incarnation",
    "product_version",
    "schema_version",
    "migration_digest",
    "algorithm",
    "key_id",
    "chunk_bytes",
    "plaintext_bytes",
    "plaintext_sha256",
    "ciphertext_bytes",
    "ciphertext_sha256",
    "state",
    "created_at",
    "verified_at",
    "deleted_at",
  ],
  restore_operations: [
    "id",
    "backup_id",
    "target_authority_incarnation",
    "state",
    "source_schema_version",
    "target_schema_version",
    "staged_database_digest",
    "revision",
    "created_at",
    "updated_at",
    "completed_at",
  ],
  backup_retention_state: [
    "deployment_id",
    "maximum_verified_backups",
    "maximum_age_seconds",
    "minimum_usable_backups",
    "revision",
    "updated_at",
  ],
  personal_run_presets: [
    "id",
    "owner_member_id",
    "project_id",
    "display_name",
    "state",
    "current_version",
    "revision",
    "created_at",
    "updated_at",
    "archived_at",
  ],
  personal_run_preset_versions: [
    "preset_id",
    "version",
    "derived_template_id",
    "derived_template_version",
    "runner_id",
    "runner_epoch",
    "mapping_revision",
    "profile_id",
    "profile_version",
    "profile_fingerprint",
    "host",
    "interaction",
    "repository_mode",
    "repository_assurance",
    "execution_policy",
    "maximum_attempts",
    "deadline_seconds",
    "managed_loop_max_iterations",
    "managed_loop_cadence_seconds",
    "stop_policy_digest",
    "unknown_grace_seconds",
    "unknown_backoff_initial_seconds",
    "unknown_backoff_max_seconds",
    "context_recipe_id",
    "context_recipe_version",
    "reusable_goal_template",
    "reusable_instruction_template",
    "personal_addendum",
    "configuration_digest",
    "created_at",
  ],
  personal_run_preset_gates: [
    "preset_id",
    "preset_version",
    "ordinal",
    "gate_name",
    "manifest_fingerprint",
    "required",
  ],
  personal_run_preset_stop_nodes: [
    "preset_id",
    "preset_version",
    "node_id",
    "parent_node_id",
    "ordinal",
    "node_kind",
    "subject_id",
    "expected_value",
    "match_count",
  ],
  project_personal_preset_defaults: [
    "owner_member_id",
    "project_id",
    "preset_id",
    "preset_version",
    "revision",
    "updated_at",
  ],
  context_recipes: [
    "id",
    "project_id",
    "display_name",
    "current_version",
    "state",
    "revision",
    "created_at",
    "updated_at",
    "archived_at",
  ],
  context_recipe_versions: [
    "recipe_id",
    "version",
    "include_goal",
    "include_coordination",
    "include_sources",
    "include_repository",
    "include_predecessor_evidence",
    "maximum_references",
    "maximum_preview_bytes",
    "freshness_seconds",
    "predecessor_policy",
    "recipe_digest",
    "created_at",
  ],
  context_recipe_category_limits: ["recipe_id", "recipe_version", "category", "maximum_references"],
  run_configuration_snapshots: [
    "run_id",
    "preset_id",
    "preset_version",
    "template_id",
    "template_version",
    "context_recipe_id",
    "context_recipe_version",
    "personal_addendum",
    "authored_run_input",
    "effective_configuration_json",
    "effective_configuration_digest",
    "assembly_digest",
    "created_at",
  ],
  context_bootstrap_envelopes: [
    "id",
    "run_id",
    "recipe_id",
    "recipe_version",
    "reference_count",
    "preview_bytes",
    "envelope_digest",
    "created_at",
  ],
  context_envelope_references: [
    "envelope_id",
    "ordinal",
    "category",
    "reference_id",
    "observed_revision",
    "freshness",
    "omission_reason",
    "preview_text",
    "preview_digest",
  ],
  attempt_usage_eligibility: [
    "attempt_id",
    "runtime_adapter",
    "profile_id",
    "profile_version",
    "provider",
    "declared_model",
    "started_at",
    "ended_at",
    "created_at",
  ],
  usage_observations: [
    "id",
    "attempt_id",
    "observation_id",
    "provider",
    "reported_model",
    "metric_category",
    "availability",
    "units",
    "observed_at",
  ],
  operational_incidents: [
    "id",
    "incident_kind",
    "correlation_id",
    "subject_id",
    "safe_code",
    "state",
    "revision",
    "created_at",
    "resolved_at",
  ],
  published_git_references: [
    "id",
    "run_id",
    "attempt_id",
    "repository_id",
    "remote_identity",
    "remote_ref",
    "commit_sha",
    "verification_digest",
    "verified_at",
    "created_at",
  ],
  retained_local_work_projections: [
    "id",
    "run_id",
    "attempt_id",
    "runner_id",
    "observation_revision",
    "observation_digest",
    "head_commit",
    "retention_reason",
    "tracked_change_count",
    "untracked_change_count",
    "changed_paths_truncated",
    "disk_bytes",
    "publish_state",
    "published_reference_id",
    "state",
    "revision",
    "observed_at",
    "updated_at",
  ],
  retained_local_work_changed_paths: [
    "retained_work_id",
    "observation_revision",
    "ordinal",
    "repository_relative_path",
  ],
};

function names(database: Database, type: "index" | "table" | "trigger"): Set<string> {
  return new Set(
    database
      .query<{ name: string }, [string]>("SELECT name FROM sqlite_master WHERE type = ?")
      .all(type)
      .map((row) => row.name),
  );
}

export function verifyFoundationOperationsSchema(database: Database): void {
  const versions = database
    .query<{ version: number }, []>("SELECT version FROM schema_migrations ORDER BY version")
    .all()
    .map((row) => row.version);
  if (
    versions.length < 5 ||
    versions.slice(0, 5).join(",") !== "1,2,3,4,5" ||
    versions.some((version, index) => version !== index + 1)
  ) {
    throw new Error("SCHEMA_MIGRATION_HISTORY_INVALID");
  }
  for (const [type, expected] of [
    ["table", FOUNDATION_OPERATION_TABLES],
    ["index", FOUNDATION_OPERATION_INDEXES],
    ["trigger", FOUNDATION_OPERATION_TRIGGERS],
  ] as const) {
    const actual = names(database, type);
    if (expected.some((name) => !actual.has(name))) throw new Error("SCHEMA_INTEGRITY_INVALID");
  }
  for (const table of FOUNDATION_OPERATION_TABLES) {
    const columns = database
      .query<{ name: string }, []>(`PRAGMA table_info('${table}')`)
      .all()
      .map((row) => row.name);
    if (
      database.query<{ strict: number }, []>(`PRAGMA table_list('${table}')`).get()?.strict !== 1 ||
      columns.join(",") !== EXPECTED_COLUMNS[table].join(",")
    ) {
      throw new Error("SCHEMA_INTEGRITY_INVALID");
    }
  }
  const objectNames = [
    ...FOUNDATION_OPERATION_TABLES,
    ...FOUNDATION_OPERATION_INDEXES,
    ...FOUNDATION_OPERATION_TRIGGERS,
  ];
  const canonicalObjects = database
    .query<{ type: string; name: string; sql: string }, string[]>(
      `SELECT type, name, sql FROM sqlite_master
       WHERE name IN (${objectNames.map(() => "?").join(",")})
       ORDER BY type, name`,
    )
    .all(...objectNames)
    .map((row) => ({ ...row, sql: row.sql.replace(/\s+/g, " ").trim() }));
  const schemaDigest = new Bun.CryptoHasher("sha256")
    .update(JSON.stringify(canonicalObjects))
    .digest("hex");
  if (schemaDigest !== FOUNDATION_OPERATIONS_SCHEMA_SHA256) {
    throw new Error("SCHEMA_INTEGRITY_INVALID");
  }
  if (
    database.query<{ quick_check: string }, []>("PRAGMA quick_check").get()?.quick_check !== "ok" ||
    database.query<Record<string, unknown>, []>("PRAGMA foreign_key_check").all().length !== 0
  ) {
    throw new Error("SCHEMA_INTEGRITY_INVALID");
  }
}
